# These are supported funding model platforms

github: srdzank
patreon: srdzank
open_collective: srdzank
ko_fi: srdzank
tidelift: srdzank
community_bridge: srdzank
liberapay: srdzank
issuehunt: srdzank
otechie: srdzank
lfx_crowdfunding: srdzank
custom: srdzank
